config/routes.rb
Rails.application.routes.draw do
  
  resources :enrollments
  get 'users/index'
  get 'home/activity'
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  resources :courses do
    resources :lessons
  end

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr 
%footer
    .container
        .row
            .col-md-4
            Copyright
            = Time.now.year
            CoursePlatform
            .col-md-4
            Privacy policy
            

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{ } E-learn
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
  %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
  - if current_user
    %ul.navbar-nav.mr-auto
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(root_path)} nav-item"}
        = link_to root_path, class: 'nav-link' do
          .fa.fa-home
          Home
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(courses_path)} nav-item"}
        = link_to courses_path, class: 'nav-link' do
          .fa.fa-book
          Courses
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(new_course_path)}"}
        = link_to new_course_path, class: 'nav-link' do
          .fa.fa-plus
          New course
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(users_path)}"}
        = link_to users_path, class: 'nav-link' do
          .fa.fa-users
          User
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
        = link_to enrollments_path, class: 'nav-link' do
          .fa.fa-lock-open
          Enrollment
    .form-inline.my-2.my-lg-0
      = form_tag(courses_path, method: :get) do
        .input-group
          = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Find a course", class: 'form-control-lg'
          %span.input-group-append
            %button.btn.btn-primary.btn-sm{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
      
    %ul.navbar-nav.mr-right
      %li.nav-item{:class => "#{'active font-weight-bold' if current_page?(home_activity_path)}"}
        = link_to home_activity_path, class: 'nav-link' do
          .fa.fa-bell
          Activities

      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
          %b= current_user.email
        .dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
          =link_to edit_user_registration_path, class: "dropdown-item" do
            .fa.fa-cog
            %b Account settings
          =link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
            .fa.fa-sign-out-alt
            %b Sign out
  - else
    %ul.navbar-nav
      %li.nav-item= link_to 'Sign up', new_user_registration_path, class: "nav-link"
      %li.nav-item= link_to 'Log in', new_user_session_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title ELearning
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/header'
    =render 'layouts/messages'
    %p.notice= notice
    %p.alert= alert
    .container

    
    = yield

    
=render 'layouts/footer'